config/routes.rb
ToDo2::Application.routes.draw do
  resources :tasks, :only => [:create, :update, :destroy]
  resources :lists, :except => [:new, :edit, :update]
  
  root to: 'lists#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :name, :presence => true
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :presence => true
  after_initialize :set_not_done
  belongs_to :list

  def self.incomplete
    Task.where(:done => false)
  end

  def self.complete
    Task.where(:done => true)
  end

private
  
  def set_not_done
    self.done ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.new
    @lists = List.all
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      flash[:notice] = "Your list has been created."
      redirect_to lists_path
    else 
      @lists = List.all
      render :index
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(lists_params)
    flash[:notice] = "Your list has been updated"
    redirect_to lists_path
    
  end

  def show
    @list = List.find(params[:id])
    @task = @list.tasks.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash[:notice] = "Your list has been deleted."
    redirect_to lists_path
  end

private
  def lists_params
    params.require(:list).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = 'Your task has been created'
      redirect_to @task.list
    else
      @list = @task.list
      render 'lists/show'
    end
  end

  def edit 
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "Your task was successfully updated"
      respond_to do |format|
        format.html { redirect_to @task.list }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Your task was successfully destroyed"
    respond_to do |format|
      format.html { redirect_to @task.list}
      format.js
    end
  end


private

  def task_params
    params.require(:task).permit(:name, :done, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="navbar">
      <a class="navbar-brand" href="#">&#x2713UDidit</a>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.any? %>
  <ul>
    <% @list.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @list do |f| %>
 <%= f.text_field :name %>
 <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
   <title>Lists</title>
   <div class="row">
      <div class="span4">
        <%= render 'form' %>
        <hr>
        <p>Your Lists</p>
        <div class="well">
          <ul>
            <% @lists.each do |list| %>
              <li><%= link_to list.name, list_path(list) %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<h4>List: <%= @list.name %></h14>   | <small><%= link_to "Delete", @list, method: :delete, date: {confirm: "Are you sure?"} %></small> | <small><%= link_to "Back to Lists", lists_path %></samll>
<hr>
<div class="container">
  <title>Tasks</title>
  <div class="row">
    <div class="span4">
      <%= render 'tasks/form' %>
      <hr>
      <p>Your Tasks</p>
      <div class="well">
        <h6>Incomplete:</h6>
        <div class="tasks" id="incomplete_tasks">
          <% @list.tasks.incomplete.each do |task| %>
            <%= render task %>
          <% end %>
        </div>
        <h6>Comlpete:</h6>
        <div class="tasks" id="complete_tasks">
          <% @list.tasks.complete.each do |task| %>
            <%= render task %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @task  do |f| %>
 <%= f.text_field :name %>
 <%= f.hidden_field :list_id %>
 <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :done %>
  <%= f.label :done, task.name %>
  <%= link_to "(remove)", task, method: :delete, date: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/update.js.erb
<% if @task.done? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>